apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: togglemaster
  labels:
    app: flag-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: 546238497113.dkr.ecr.us-east-1.amazonaws.com/tm-fiap-p3-dev-flag:a68f20773a9c3da3d8f81acd426c893a5d681b9a
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: FLAG_PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-config
                  key: AUTH_SERVICE_URL
          envFrom:
            - secretRef:
                name: flag-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 20
            periodSeconds: 20