apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: auth-secret
  namespace: togglemaster

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: auth-secret
    creationPolicy: Owner

  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: tm-fiap-p3/dev/data-services
        property: AUTH_DATABASE_URL

    - secretKey: DB_USERNAME
      remoteRef:
        key: tm-fiap-p3/dev/data-services
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: tm-fiap-p3/dev/data-services
        property: DB_PASSWORD
    - secretKey: MASTER_KEY
      remoteRef:
        key: tm-fiap-p3/dev/data-services
        property: MASTER_KEY
