apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: analytics-secret
  namespace: togglemaster

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: analytics-secret
    creationPolicy: Owner

  data:
  - secretKey: AWS_SQS_URL
    remoteRef:
      key: tm-fiap-p3/dev/data-services
      property: AWS_SQS_URL

  - secretKey: AWS_DYNAMODB_TABLE
    remoteRef:
      key: tm-fiap-p3/dev/data-services
      property: AWS_DYNAMODB_TABLE

  - secretKey: AWS_REGION
    remoteRef:
      key: tm-fiap-p3/dev/data-services
      property: AWS_REGION